name: Hello my_project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print another message
        run: echo "hello my_project"

      - name: Print second message
        run: echo "hello my_project"
