name: Hello my_project

on:
  push:
    branches: [main, dev, rt]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print a new message
        run: echo "hello my_project"
